package org.jboss.qa.ba.scesim;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Promotion implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private double discountRate;

    private java.util.List<org.jboss.qa.ba.scesim.TicketType> ticketTypes;

    public Promotion() {
    }

    public double getDiscountRate() {
        return this.discountRate;
    }

    public void setDiscountRate(double discountRate) {
        this.discountRate = discountRate;
    }

    public java.util.List<org.jboss.qa.ba.scesim.TicketType> getTicketTypes() {
        return this.ticketTypes;
    }

    public void setTicketTypes(
            java.util.List<org.jboss.qa.ba.scesim.TicketType> ticketTypes) {
        this.ticketTypes = ticketTypes;
    }

    public Promotion(double discountRate,
                     java.util.List<org.jboss.qa.ba.scesim.TicketType> ticketTypes) {
        this.discountRate = discountRate;
        this.ticketTypes = ticketTypes;
    }
}