package org.jboss.qa.ba.scesim;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Ticket implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private org.jboss.qa.ba.scesim.TicketType type;
    private java.lang.Double price;
    private java.lang.Long id;

    public Ticket() {
    }

    public org.jboss.qa.ba.scesim.TicketType getType() {
        return this.type;
    }

    public void setType(org.jboss.qa.ba.scesim.TicketType type) {
        this.type = type;
    }

    public java.lang.Double getPrice() {
        return this.price;
    }

    public void setPrice(java.lang.Double price) {
        this.price = price;
    }

    public java.lang.Long getId() {
        return this.id;
    }

    public void setId(java.lang.Long id) {
        this.id = id;
    }

    public Ticket(org.jboss.qa.ba.scesim.TicketType type,
                  java.lang.Double price, java.lang.Long id) {
        this.type = type;
        this.price = price;
        this.id = id;
    }
}